parameters:
  smile.legacy.publish.handler.class: Smile\LegacyPublishHandlerBundle\Services\LegacyPublishHandler

services:
    smile.legacy.publish.handler:
        class: '%smile.legacy.publish.handler.class%'
        arguments:
        - "@ezpublish.api.repository"
        - !tagged smile.legacy_publish_handler