parameters:
  legacy.publish.handler.class: SteveCohenFr\LegacyPublishHandlerBundle\Services\LegacyPublishHandler

services:
    stevecohenfr.legacy.publish.handler:
        class: '%legacy.publish.handler.class%'
        arguments:
        - "@ezpublish.api.repository"